# Generated by Django 3.2.8 on 2021-10-28 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tgl_lahir',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
