# Generated by Django 3.2.8 on 2021-11-08 07:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpj',
            name='is_aktif',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('86aba3f2-10ec-49ab-a534-8373936fc8e5'), editable=False),
        ),
    ]
