# Generated by Django 3.2.8 on 2021-10-28 14:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('1496d849-2769-4d11-ac26-186ecc6fa559'), editable=False),
        ),
    ]
