# Generated by Django 3.2.8 on 2021-10-28 14:55

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0002_alter_toqrcode_url_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatk',
            name='file_buku_nikah',
        ),
        migrations.AddField(
            model_name='datatk',
            name='file_paklaring',
            field=models.FileField(upload_to='tk/paklaring/', validators=[django.core.validators.RegexValidator(
                '.*\\.(jpg|JPG|JPEG|pdf|PDF)', 'Only Support PDF dan JPG')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datatk',
            name='file_kk',
            field=models.FileField(blank=True, null=True, upload_to='tk/kk/', validators=[
                                   django.core.validators.RegexValidator('.*\\.(jpg|JPG|JPEG|pdf|PDF)', 'Only Support PDF dan JPG')]),
        ),
        migrations.AlterField(
            model_name='datatk',
            name='file_ktp',
            field=models.FileField(blank=True, null=True, upload_to='tk/ktp/', validators=[
                                   django.core.validators.RegexValidator('.*\\.(jpg|JPG|JPEG|pdf|PDF)', 'Only Support PDF dan JPG')]),
        ),
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID(
                '5682287a-c8ae-439f-b264-817ba05d3318'), editable=False),
        ),
    ]
