# Generated by Django 3.2.8 on 2021-10-29 03:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0003_auto_20211028_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('4bf6e749-b05d-4c78-9718-9feee2fd1f7a'), editable=False),
        ),
    ]
