# Generated by Django 3.2.8 on 2021-10-29 08:56

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0004_alter_toqrcode_url_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatk',
            name='file_paklaring',
            field=models.FileField(blank=True, null=True, upload_to='tk/paklaring/', validators=[django.core.validators.RegexValidator('.*\\.(jpg|JPG|JPEG|pdf|PDF)', 'Only Support PDF dan JPG')]),
        ),
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('52caedd0-3d42-4b63-8a35-3d298cc3bc6d'), editable=False),
        ),
    ]
