# Generated by Django 3.2.8 on 2021-10-29 08:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0005_auto_20211029_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('704914dd-5632-4763-94eb-13bc044b487f'), editable=False),
        ),
    ]
