# Generated by Django 3.2.8 on 2021-11-01 15:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0006_alter_toqrcode_url_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpj',
            name='no_kpj',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='kpj',
            name='tgl_keps',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kpj',
            name='tgl_na',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('0f2c5f81-d302-4730-a0cb-064bffaadfe9'), editable=False),
        ),
    ]
