# Generated by Django 3.2.8 on 2021-11-07 14:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0007_auto_20211101_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('04b39817-6cac-448a-b949-eaaf923f1d76'), editable=False),
        ),
    ]
